// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvy8sljOTu_klN1QTfv7OsK0P46hCOfnw',
    appId: '1:290432062994:web:4a9ec3a9431354ddb3eacb',
    messagingSenderId: '290432062994',
    projectId: 'jokesappfirebase',
    authDomain: 'jokesappfirebase.firebaseapp.com',
    storageBucket: 'jokesappfirebase.firebasestorage.app',
    measurementId: 'G-NXWSCWYB2Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzKcnAY1b4TI2ovVCJxzo81YcOuTDVOGc',
    appId: '1:290432062994:android:7355e6a530856a5bb3eacb',
    messagingSenderId: '290432062994',
    projectId: 'jokesappfirebase',
    storageBucket: 'jokesappfirebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjfXja4g13nNChQcSz1VVFCbQGGFky06I',
    appId: '1:290432062994:ios:37fea699d804d8c2b3eacb',
    messagingSenderId: '290432062994',
    projectId: 'jokesappfirebase',
    storageBucket: 'jokesappfirebase.firebasestorage.app',
    iosBundleId: 'com.example.jokesAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjfXja4g13nNChQcSz1VVFCbQGGFky06I',
    appId: '1:290432062994:ios:37fea699d804d8c2b3eacb',
    messagingSenderId: '290432062994',
    projectId: 'jokesappfirebase',
    storageBucket: 'jokesappfirebase.firebasestorage.app',
    iosBundleId: 'com.example.jokesAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvy8sljOTu_klN1QTfv7OsK0P46hCOfnw',
    appId: '1:290432062994:web:c52e22c96eef7159b3eacb',
    messagingSenderId: '290432062994',
    projectId: 'jokesappfirebase',
    authDomain: 'jokesappfirebase.firebaseapp.com',
    storageBucket: 'jokesappfirebase.firebasestorage.app',
    measurementId: 'G-RLPESYG0V1',
  );
}
